In [10]:
import pandas as pd
import re #for treating special characters
import os

In [11]:
%cd "C:/Users/HP/Documents/POWER BI PROJECTS/KAGGLE 2021 DATA SCIENCE AND MACHINE LEARNING SURVEY"

C:\Users\HP\Documents\POWER BI PROJECTS\KAGGLE 2021 DATA SCIENCE AND MACHINE LEARNING SURVEY

In [12]:
#To get the present working directory (pwd)
pwd = os.getcwd()

In [13]:
data = pd.read_excel(pwd + "\\Data_kaggle_survey_2021_responses_copyy.xlsx", sheet_name = "Edited_Data")

In [14]:
data.head()

,Unique_ID,Time from Start to Finish (seconds),Q1,Q2,Q3,Q4,Q5,Q6,Q7_Part_1-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - Python,Q7_Part_2-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - R,...,"Q38_B_Part_3-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - Comet.ml","Q38_B_Part_4-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - Sacred + Omniboard","Q38_B_Part_5-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - TensorBoard","Q38_B_Part_6-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - Guild.ai","Q38_B_Part_7-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - Polyaxon","Q38_B_Part_8-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - ClearML","Q38_B_Part_9-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - Domino Model Monitor","Q38_B_Part_10-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - MLflow","Q38_B_Part_11-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - None","Q38_B_OTHER-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - Other"
0,1,910,50-54,Man,India,Bachelorâ€™s degree,Other,5-10 years,Python,R,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,784,50-54,Man,Indonesia,Masterâ€™s degree,Program/Project Manager,20+ years,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
2,3,924,22-24,Man,Pakistan,Masterâ€™s degree,Software Engineer,1-3 years,Python,NaN,...,NaN,NaN,TensorBoard,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,575,45-49,Man,Mexico,Doctoral degree,Research Scientist,20+ years,Python,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
4,5,781,45-49,Man,India,Doctoral degree,Other,< 1 years,Python,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
data.shape

(25973, 370)

In [16]:
#Create a copy of the dataframe so i can easily rollback 
#incase there is a mistake instead of imprting the entire dataset (which is heavy)

In [17]:
data_copy = data

In [18]:
#Viewing the column names so I can drop the unneccesary columns easily
data_copy.columns

Index(['Unique_ID', 'Time from Start to Finish (seconds)', 'Q1', 'Q2', 'Q3',
       'Q4', 'Q5', 'Q6',
       'Q7_Part_1-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - Python',
       'Q7_Part_2-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - R',
       ...
       'Q38_B_Part_3-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice -  Comet.ml ',
       'Q38_B_Part_4-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice -  Sacred + Omniboard ',
       'Q38_B_Part_5-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice -  TensorBoard ',
       'Q38_B_Part_6-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice -  Guild.ai ',
       'Q38_B_Part_7-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice -  Polyaxon ',
       'Q38_B_Part_8-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice -  ClearML ',
       'Q38_B_Part_9-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice -  Domino Model Monitor ',
       'Q38_B_Part_10-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice -  MLflow ',
       'Q38_B_Part_11-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - None',
       'Q38_B_OTHER-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - Other'],
      dtype='object', length=370)

In [19]:
#Remove unwanted columns as we won't be needing them for the analysis
unwanted_column = ["Time from Start to Finish (seconds)"]
unwanted_column

['Time from Start to Finish (seconds)']

In [20]:
data_copy = data_copy.drop(columns = unwanted_column)
data_copy

,Unique_ID,Q1,Q2,Q3,Q4,Q5,Q6,Q7_Part_1-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - Python,Q7_Part_2-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - R,Q7_Part_3-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - SQL,...,"Q38_B_Part_3-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - Comet.ml","Q38_B_Part_4-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - Sacred + Omniboard","Q38_B_Part_5-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - TensorBoard","Q38_B_Part_6-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - Guild.ai","Q38_B_Part_7-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - Polyaxon","Q38_B_Part_8-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - ClearML","Q38_B_Part_9-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - Domino Model Monitor","Q38_B_Part_10-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - MLflow","Q38_B_Part_11-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - None","Q38_B_OTHER-In the next 2 years, do you hope to become more familiar with any of these tools for managing ML experiments? (Select all that apply) - Selected Choice - Other"
0,1,50-54,Man,India,Bachelorâ€™s degree,Other,5-10 years,Python,R,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,50-54,Man,Indonesia,Masterâ€™s degree,Program/Project Manager,20+ years,NaN,NaN,SQL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
2,3,22-24,Man,Pakistan,Masterâ€™s degree,Software Engineer,1-3 years,Python,NaN,NaN,...,NaN,NaN,TensorBoard,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,45-49,Man,Mexico,Doctoral degree,Research Scientist,20+ years,Python,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
4,5,45-49,Man,India,Doctoral degree,Other,< 1 years,Python,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25968,25969,30-34,Man,Egypt,Bachelorâ€™s degree,Data Analyst,1-3 years,Python,NaN,SQL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25969,25970,22-24,Man,China,Masterâ€™s degree,Student,1-3 years,Python,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25970,25971,50-54,Man,Sweden,Doctoral degree,Research Scientist,I have never written code,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
25971,25972,45-49,Man,United States of America,Masterâ€™s degree,Data Scientist,5-10 years,Python,NaN,SQL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25972,25973,18-21,Man,India,Bachelorâ€™s degree,Business Analyst,I have never written code,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN

In [21]:
id_vars = list(data_copy.columns[:7])
id_vars

['Unique_ID', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6']

In [22]:
data_questions = list(data_copy.columns[7:])
data_questions

['Q7_Part_1-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - Python',
 'Q7_Part_2-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - R',
 'Q7_Part_3-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - SQL',
 'Q7_Part_4-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - C',
 'Q7_Part_5-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - C++',
 'Q7_Part_6-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - Java',
 'Q7_Part_7-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - Javascript',
 'Q7_Part_8-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - Julia',
 'Q7_Part_9-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - Swift',
 'Q7_Part_10-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - Bash',
 'Q7_Part_11-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - MATLAB',
 'Q7_Part_12-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - None',
 'Q7_OTHER-What programming languages do you use on a regular basis? (Select all that apply) - Selected Choice - Other',
 'Q8-What programming language would you recommend an aspiring data scientist to learn first? - Selected Choice',
 "Q9_Part_1-Which of the following integrated development environments (IDE's) do you use on a regular basis?  (Select all that apply) - Selected Choice - Jupyter (JupyterLab, Jupyter Notebooks, etc) ",
 "Q9_Part_2-Which of the following integrated development environments (IDE's) do you use on a regular basis?  (Select all that apply) - Selected Choice -  RStudio ",
 "Q9_Part_3-Which of the following integrated development environments (IDE's) do you use on a regular basis?  (Select all that apply) - Selected Choice -  Visual Studio ",
 "Q9_Part_4-Which of the following integrated development environments (IDE's) do you use on a regular basis?  (Select all that apply) - Selected Choice -  Visual Studio Code (VSCode) ",
 "Q9_Part_5-Which of the following integrated development environments (IDE's) do you use on a regular basis?  (Select all that apply) - Selected Choice -  PyCharm ",
 "Q9_Part_6-Which of the following integrated development environments (IDE's) do you use on a regular basis?  (Select all that apply) - Selected Choice -   Spyder  ",
 "Q9_Part_7-Which of the following integrated development environments (IDE's) do you use on a regular basis?  (Select all that apply) - Selected Choice -   Notepad++  ",
 "Q9_Part_8-Which of the following integrated development environments (IDE's) do you use on a regular basis?  (Select all that apply) - Selected Choice -   Sublime Text  ",
 "Q9_Part_9-Which of the following integrated development environments (IDE's) do you use on a regular basis?  (Select all that apply) - Selected Choice -   Vim / Emacs  ",
 "Q9_Part_10-Which of the following integrated development environments (IDE's) do you use on a regular basis?  (Select all that apply) - Selected Choice -  MATLAB ",
 "Q9_Part_11-Which of the following integrated development environments (IDE's) do you use on a regular basis?  (Select all that apply) - Selected Choice -  Jupyter Notebook",
 "Q9_Part_12-Which of the following integrated development environments (IDE's) do you use on a regular basis?  (Select all that apply) - Selected Choice - None",
 "Q9_OTHER-Which of the following integrated development environments (IDE's) do you use on a regular basis?  (Select all that apply) - Selected Choice - Other",
 'Q10_Part_1-Which of the following hosted notebook products do you use on a regular basis?  (Select all that apply) - Selected Choice -  Kaggle Notebooks',
 'Q10_Part_2-Which of the following hosted notebook products do you use on a regular basis?  (Select all that apply) - Selected Choice - Colab Notebooks',
 'Q10_Part_3-Which of the following hosted notebook products do you use on a regular basis?  (Select all that apply) - Selected Choice - Azure Notebooks',
 'Q10_Part_4-Which of the following hosted notebook products do you use on a regular basis?  (Select all that apply) - Selected Choice -  Paperspace / Gradient ',
 'Q10_Part_5-Which of the following hosted notebook products do you use on a regular basis?  (Select all that apply) - Selected Choice -  Binder / JupyterHub ',
 'Q10_Part_6-Which of the following hosted notebook products do you use on a regular basis?  (Select all that apply) - Selected Choice -  Code Ocean ',
 'Q10_Part_7-Which of the following hosted notebook products do you use on a regular basis?  (Select all that apply) - Selected Choice -  IBM Watson Studio ',
 'Q10_Part_8-Which of the following hosted notebook products do you use on a regular basis?  (Select all that apply) - Selected Choice -  Amazon Sagemaker Studio Notebooks ',
 'Q10_Part_9-Which of the following hosted notebook products do you use on a regular basis?  (Select all that apply) - Selected Choice -  Amazon EMR Notebooks ',
 'Q10_Part_10-Which of the following hosted notebook products do you use on a regular basis?  (Select all that apply) - Selected Choice - Google Cloud Notebooks (AI Platform / Vertex AI) ',
 'Q10_Part_11-Which of the following hosted notebook products do you use on a regular basis?  (Select all that apply) - Selected Choice - Google Cloud Datalab',
 'Q10_Part_12-Which of the following hosted notebook products do you use on a regular basis?  (Select all that apply) - Selected Choice -  Databricks Collaborative Notebooks ',
 'Q10_Part_13-Which of the following hosted notebook products do you use on a regular basis?  (Select all that apply) - Selected Choice -  Zeppelin / Zepl Notebooks ',
 'Q10_Part_14-Which of the following hosted notebook products do you use on a regular basis?  (Select all that apply) - Selected Choice -  Deepnote Notebooks ',
 'Q10_Part_15-Which of the following hosted notebook products do you use on a regular basis?  (Select all that apply) - Selected Choice -  Observable Notebooks ',
 'Q10_Part_16-Which of the following hosted notebook products do you use on a regular basis?  (Select all that apply) - Selected Choice - None',
 'Q10_OTHER-Which of the following hosted notebook products do you use on a regular basis?  (Select all that apply) - Selected Choice - Other',
 'Q11-What type of computing platform do you use most often for your data science projects? - Selected Choice',
 'Q12_Part_1-Which types of specialized hardware do you use on a regular basis?  (Select all that apply) - Selected Choice -  NVIDIA GPUs ',
 'Q12_Part_2-Which types of specialized hardware do you use on a regular basis?  (Select all that apply) - Selected Choice -  Google Cloud TPUs ',
 'Q12_Part_3-Which types of specialized hardware do you use on a regular basis?  (Select all that apply) - Selected Choice -  AWS Trainium Chips ',
 'Q12_Part_4-Which types of specialized hardware do you use on a regular basis?  (Select all that apply) - Selected Choice -  AWS Inferentia Chips ',
 'Q12_Part_5-Which types of specialized hardware do you use on a regular basis?  (Select all that apply) - Selected Choice - None',
 'Q12_OTHER-Which types of specialized hardware do you use on a regular basis?  (Select all that apply) - Selected Choice - Other',
 'Q13-Approximately how many times have you used a TPU (tensor processing unit)?',
 'Q14_Part_1-What data visualization libraries or tools do you use on a regular basis?  (Select all that apply) - Selected Choice -  Matplotlib ',
 'Q14_Part_2-What data visualization libraries or tools do you use on a regular basis?  (Select all that apply) - Selected Choice -  Seaborn ',
 'Q14_Part_3-What data visualization libraries or tools do you use on a regular basis?  (Select all that apply) - Selected Choice -  Plotly / Plotly Express ',
 'Q14_Part_4-What data visualization libraries or tools do you use on a regular basis?  (Select all that apply) - Selected Choice -  Ggplot / ggplot2 ',
 'Q14_Part_5-What data visualization libraries or tools do you use on a regular basis?  (Select all that apply) - Selected Choice -  Shiny ',
 'Q14_Part_6-What data visualization libraries or tools do you use on a regular basis?  (Select all that apply) - Selected Choice -  D3 js ',
 'Q14_Part_7-What data visualization libraries or tools do you use on a regular basis?  (Select all that apply) - Selected Choice -  Altair ',
 'Q14_Part_8-What data visualization libraries or tools do you use on a regular basis?  (Select all that apply) - Selected Choice -  Bokeh ',
 'Q14_Part_9-What data visualization libraries or tools do you use on a regular basis?  (Select all that apply) - Selected Choice -  Geoplotlib ',
 'Q14_Part_10-What data visualization libraries or tools do you use on a regular basis?  (Select all that apply) - Selected Choice -  Leaflet / Folium ',
 'Q14_Part_11-What data visualization libraries or tools do you use on a regular basis?  (Select all that apply) - Selected Choice - None',
 'Q14_OTHER-What data visualization libraries or tools do you use on a regular basis?  (Select all that apply) - Selected Choice - Other',
 'Q15-For how many years have you used machine learning methods?',
 'Q16_Part_1-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice -   Scikit-learn ',
 'Q16_Part_2-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice -   TensorFlow ',
 'Q16_Part_3-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice -  Keras ',
 'Q16_Part_4-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice -  PyTorch ',
 'Q16_Part_5-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice -  Fast.ai ',
 'Q16_Part_6-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice -  MXNet ',
 'Q16_Part_7-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice -  Xgboost ',
 'Q16_Part_8-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice -  LightGBM ',
 'Q16_Part_9-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice -  CatBoost ',
 'Q16_Part_10-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice -  Prophet ',
 'Q16_Part_11-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice -  H2O 3 ',
 'Q16_Part_12-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice -  Caret ',
 'Q16_Part_13-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice -  Tidymodels ',
 'Q16_Part_14-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice -  JAX ',
 'Q16_Part_15-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice -  PyTorch Lightning ',
 'Q16_Part_16-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice -  Huggingface ',
 'Q16_Part_17-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice - None',
 'Q16_OTHER-Which of the following machine learning frameworks do you use on a regular basis? (Select all that apply) - Selected Choice - Other',
 'Q17_Part_1-Which of the following ML algorithms do you use on a regular basis? (Select all that apply): - Selected Choice - Linear or Logistic Regression',
 'Q17_Part_2-Which of the following ML algorithms do you use on a regular basis? (Select all that apply): - Selected Choice - Decision Trees or Random Forests',
 'Q17_Part_3-Which of the following ML algorithms do you use on a regular basis? (Select all that apply): - Selected Choice - Gradient Boosting Machines (xgboost, lightgbm, etc)',
 'Q17_Part_4-Which of the following ML algorithms do you use on a regular basis? (Select all that apply): - Selected Choice - Bayesian Approaches',
 'Q17_Part_5-Which of the following ML algorithms do you use on a regular basis? (Select all that apply): - Selected Choice - Evolutionary Approaches',
 'Q17_Part_6-Which of the following ML algorithms do you use on a regular basis? (Select all that apply): - Selected Choice - Dense Neural Networks (MLPs, etc)',
 'Q17_Part_7-Which of the following ML algorithms do you use on a regular basis? (Select all that apply): - Selected Choice - Convolutional Neural Networks',
 'Q17_Part_8-Which of the following ML algorithms do you use on a regular basis? (Select all that apply): - Selected Choice - Generative Adversarial Networks',
 'Q17_Part_9-Which of the following ML algorithms do you use on a regular basis? (Select all that apply): - Selected Choice - Recurrent Neural Networks',
 'Q17_Part_10-Which of the following ML algorithms do you use on a regular basis? (Select all that apply): - Selected Choice - Transformer Networks (BERT, gpt-3, etc)',
 'Q17_Part_11-Which of the following ML algorithms do you use on a regular basis? (Select all that apply): - Selected Choice - None',
 'Q17_OTHER-Which of the following ML algorithms do you use on a regular basis? (Select all that apply): - Selected Choice - Other',
 'Q18_Part_1-Which categories of computer vision methods do you use on a regular basis?  (Select all that apply) - Selected Choice - General purpose image/video tools (PIL, cv2, skimage, etc)',
 'Q18_Part_2-Which categories of computer vision methods do you use on a regular basis?  (Select all that apply) - Selected Choice - Image segmentation methods (U-Net, Mask R-CNN, etc)',
 'Q18_Part_3-Which categories of computer vision methods do you use on a regular basis?  (Select all that apply) - Selected Choice - Object detection methods (YOLOv3, RetinaNet, etc)',
 'Q18_Part_4-Which categories of computer vision methods do you use on a regular basis?  (Select all that apply) - Selected Choice - Image classification and other general purpose networks (VGG, Inception, ResNet, ResNeXt, NASNet, EfficientNet, etc)',
 'Q18_Part_5-Which categories of computer vision methods do you use on a regular basis?  (Select all that apply) - Selected Choice - Generative Networks (GAN, VAE, etc)',
 'Q18_Part_6-Which categories of computer vision methods do you use on a regular basis?  (Select all that apply) - Selected Choice - None',
 'Q18_OTHER-Which categories of computer vision methods do you use on a regular basis?  (Select all that apply) - Selected Choice - Other',
 'Q19_Part_1-Which of the following natural language processing (NLP) methods do you use on a regular basis?  (Select all that apply) - Selected Choice - Word embeddings/vectors (GLoVe, fastText, word2vec)',
 'Q19_Part_2-Which of the following natural language processing (NLP) methods do you use on a regular basis?  (Select all that apply) - Selected Choice - Encoder-decorder models (seq2seq, vanilla transformers)',
 'Q19_Part_3-Which of the following natural language processing (NLP) methods do you use on a regular basis?  (Select all that apply) - Selected Choice - Contextualized embeddings (ELMo, CoVe)',
 'Q19_Part_4-Which of the following natural language processing (NLP) methods do you use on a regular basis?  (Select all that apply) - Selected Choice - Transformer language models (GPT-3, BERT, XLnet, etc)',
 'Q19_Part_5-Which of the following natural language processing (NLP) methods do you use on a regular basis?  (Select all that apply) - Selected Choice - None',
 'Q19_OTHER-Which of the following natural language processing (NLP) methods do you use on a regular basis?  (Select all that apply) - Selected Choice - Other',
 'Q20-In what industry is your current employer/contract (or your most recent employer if retired)? - Selected Choice',
 'Q21-What is the size of the company where you are employed?',
 'Q22-Approximately how many individuals are responsible for data science workloads at your place of business?',
 'Q23-Does your current employer incorporate machine learning methods into their business?',
 'Q24_Part_1-Select any activities that make up an important part of your role at work: (Select all that apply) - Selected Choice - Analyze and understand data to influence product or business decisions',
 'Q24_Part_2-Select any activities that make up an important part of your role at work: (Select all that apply) - Selected Choice - Build and/or run the data infrastructure that my business uses for storing, analyzing, and operationalizing data',
 'Q24_Part_3-Select any activities that make up an important part of your role at work: (Select all that apply) - Selected Choice - Build prototypes to explore applying machine learning to new areas',
 'Q24_Part_4-Select any activities that make up an important part of your role at work: (Select all that apply) - Selected Choice - Build and/or run a machine learning service that operationally improves my product or workflows',
 'Q24_Part_5-Select any activities that make up an important part of your role at work: (Select all that apply) - Selected Choice - Experimentation and iteration to improve existing ML models',
 'Q24_Part_6-Select any activities that make up an important part of your role at work: (Select all that apply) - Selected Choice - Do research that advances the state of the art of machine learning',
 'Q24_Part_7-Select any activities that make up an important part of your role at work: (Select all that apply) - Selected Choice - None of these activities are an important part of my role at work',
 'Q24_OTHER-Select any activities that make up an important part of your role at work: (Select all that apply) - Selected Choice - Other',
 'Q25-What is your current yearly compensation (approximate $USD)?',
 'Q26-Approximately how much money have you (or your team) spent on machine learning and/or cloud computing services at home (or at work) in the past 5 years (approximate $USD)?',
 'Q27_A_Part_1-Which of the following cloud computing platforms do you use on a regular basis? (Select all that apply) - Selected Choice -  Amazon Web Services (AWS) ',
 'Q27_A_Part_2-Which of the following cloud computing platforms do you use on a regular basis? (Select all that apply) - Selected Choice -  Microsoft Azure ',
 'Q27_A_Part_3-Which of the following cloud computing platforms do you use on a regular basis? (Select all that apply) - Selected Choice -  Google Cloud Platform (GCP) ',
 'Q27_A_Part_4-Which of the following cloud computing platforms do you use on a regular basis? (Select all that apply) - Selected Choice -  IBM Cloud / Red Hat ',
 'Q27_A_Part_5-Which of the following cloud computing platforms do you use on a regular basis? (Select all that apply) - Selected Choice -  Oracle Cloud ',
 'Q27_A_Part_6-Which of the following cloud computing platforms do you use on a regular basis? (Select all that apply) - Selected Choice -  SAP Cloud ',
 'Q27_A_Part_7-Which of the following cloud computing platforms do you use on a regular basis? (Select all that apply) - Selected Choice -  Salesforce Cloud ',

In [23]:
#Unpivot the table using the melt function
data_copy_melted = data_copy.melt(id_vars = id_vars, value_vars = data_questions, var_name = "Question+Subquestion", value_name = "Answer")
data_copy_melted

,Unique_ID,Q1,Q2,Q3,Q4,Q5,Q6,Question+Subquestion,Answer
0,1,50-54,Man,India,Bachelorâ€™s degree,Other,5-10 years,Q7_Part_1-What programming languages do you us...,Python
1,2,50-54,Man,Indonesia,Masterâ€™s degree,Program/Project Manager,20+ years,Q7_Part_1-What programming languages do you us...,NaN
2,3,22-24,Man,Pakistan,Masterâ€™s degree,Software Engineer,1-3 years,Q7_Part_1-What programming languages do you us...,Python
3,4,45-49,Man,Mexico,Doctoral degree,Research Scientist,20+ years,Q7_Part_1-What programming languages do you us...,Python
4,5,45-49,Man,India,Doctoral degree,Other,< 1 years,Q7_Part_1-What programming languages do you us...,Python
...,...,...,...,...,...,...,...,...,...
9402221,25969,30-34,Man,Egypt,Bachelorâ€™s degree,Data Analyst,1-3 years,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN
9402222,25970,22-24,Man,China,Masterâ€™s degree,Student,1-3 years,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN
9402223,25971,50-54,Man,Sweden,Doctoral degree,Research Scientist,I have never written code,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN
9402224,25972,45-49,Man,United States of America,Masterâ€™s degree,Data Scientist,5-10 years,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN
9402225,25973,18-21,Man,India,Bachelorâ€™s degree,Business Analyst,I have never written code,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN

In [24]:
ques_data = pd.read_excel(pwd + "\\Data_kaggle_survey_2021_responses_copyy.xlsx", sheet_name = "Questions")

In [25]:
ques_data

,Question,Subquestion,Question+Subquestion
0,Serial_number,Unique_ID,Serial_number
1,Time from Start to Finish (seconds),Duration (in seconds),Time from Start to Finish (seconds)
2,Q1,What is your age (# years)?,Q1
3,Q2,What is your gender? - Selected Choice,Q2
4,Q3,In which country do you currently reside?,Q3
...,...,...,...
365,Q38_B_Part_8,"In the next 2 years, do you hope to become mor...","Q38_B_Part_8-In the next 2 years, do you hope ..."
366,Q38_B_Part_9,"In the next 2 years, do you hope to become mor...","Q38_B_Part_9-In the next 2 years, do you hope ..."
367,Q38_B_Part_10,"In the next 2 years, do you hope to become mor...","Q38_B_Part_10-In the next 2 years, do you hope..."
368,Q38_B_Part_11,"In the next 2 years, do you hope to become mor...","Q38_B_Part_11-In the next 2 years, do you hope..."
369,Q38_B_OTHER,"In the next 2 years, do you hope to become mor...","Q38_B_OTHER-In the next 2 years, do you hope t..."

In [26]:
#Drop unwanted column(s)
#make a duplicate of the data
questions = ques_data.copy()

In [27]:
questions.drop(columns = "Subquestion", inplace = True)

In [28]:
questions

,Question,Question+Subquestion
0,Serial_number,Serial_number
1,Time from Start to Finish (seconds),Time from Start to Finish (seconds)
2,Q1,Q1
3,Q2,Q2
4,Q3,Q3
...,...,...
365,Q38_B_Part_8,"Q38_B_Part_8-In the next 2 years, do you hope ..."
366,Q38_B_Part_9,"Q38_B_Part_9-In the next 2 years, do you hope ..."
367,Q38_B_Part_10,"Q38_B_Part_10-In the next 2 years, do you hope..."
368,Q38_B_Part_11,"Q38_B_Part_11-In the next 2 years, do you hope..."
369,Q38_B_OTHER,"Q38_B_OTHER-In the next 2 years, do you hope t..."

In [29]:
#Merge both pivoted (melted df) and questions df using the join statement
alldata = pd.merge(data_copy_melted, questions, how='left', on= "Question+Subquestion")

In [30]:
alldata

,Unique_ID,Q1,Q2,Q3,Q4,Q5,Q6,Question+Subquestion,Answer,Question
0,1,50-54,Man,India,Bachelorâ€™s degree,Other,5-10 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
1,2,50-54,Man,Indonesia,Masterâ€™s degree,Program/Project Manager,20+ years,Q7_Part_1-What programming languages do you us...,NaN,Q7_Part_1
2,3,22-24,Man,Pakistan,Masterâ€™s degree,Software Engineer,1-3 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
3,4,45-49,Man,Mexico,Doctoral degree,Research Scientist,20+ years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
4,5,45-49,Man,India,Doctoral degree,Other,< 1 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
...,...,...,...,...,...,...,...,...,...,...
9402221,25969,30-34,Man,Egypt,Bachelorâ€™s degree,Data Analyst,1-3 years,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN,Q38_B_OTHER
9402222,25970,22-24,Man,China,Masterâ€™s degree,Student,1-3 years,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN,Q38_B_OTHER
9402223,25971,50-54,Man,Sweden,Doctoral degree,Research Scientist,I have never written code,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN,Q38_B_OTHER
9402224,25972,45-49,Man,United States of America,Masterâ€™s degree,Data Scientist,5-10 years,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN,Q38_B_OTHER
9402225,25973,18-21,Man,India,Bachelorâ€™s degree,Business Analyst,I have never written code,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN,Q38_B_OTHER

In [31]:
alldata.head(20)

,Unique_ID,Q1,Q2,Q3,Q4,Q5,Q6,Question+Subquestion,Answer,Question
0,1,50-54,Man,India,Bachelorâ€™s degree,Other,5-10 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
1,2,50-54,Man,Indonesia,Masterâ€™s degree,Program/Project Manager,20+ years,Q7_Part_1-What programming languages do you us...,NaN,Q7_Part_1
2,3,22-24,Man,Pakistan,Masterâ€™s degree,Software Engineer,1-3 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
3,4,45-49,Man,Mexico,Doctoral degree,Research Scientist,20+ years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
4,5,45-49,Man,India,Doctoral degree,Other,< 1 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
5,6,25-29,Woman,India,I prefer not to answer,Currently not employed,< 1 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
6,7,18-21,Woman,India,Some college/university study without earning ...,Student,1-3 years,Q7_Part_1-What programming languages do you us...,NaN,Q7_Part_1
7,8,30-34,Man,India,Bachelorâ€™s degree,Data Scientist,5-10 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
8,9,22-24,Man,Russia,Bachelorâ€™s degree,Currently not employed,3-5 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
9,10,30-34,Man,Turkey,I prefer not to answer,Other,1-3 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
10,11,40-44,Man,Australia,Doctoral degree,Other,1-3 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
11,12,18-21,Woman,India,Masterâ€™s degree,Student,< 1 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
12,13,18-21,Woman,India,Masterâ€™s degree,Student,< 1 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
13,14,45-49,Man,Nigeria,Masterâ€™s degree,Program/Project Manager,5-10 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
14,15,22-24,Man,Nigeria,Bachelorâ€™s degree,Other,< 1 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
15,16,35-39,Man,Greece,Doctoral degree,Research Scientist,10-20 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
16,17,50-54,Man,Belgium,Bachelorâ€™s degree,Data Analyst,20+ years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
17,18,18-21,Man,Pakistan,Bachelorâ€™s degree,Data Scientist,1-3 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
18,19,22-24,Man,Japan,Masterâ€™s degree,Software Engineer,3-5 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1
19,20,30-34,Man,Egypt,Bachelorâ€™s degree,Other,< 1 years,Q7_Part_1-What programming languages do you us...,NaN,Q7_Part_1

In [32]:
#Count the number of responses to particular questions by grouping by question and counting by the Answer column
respondents = alldata.groupby("Question")["Answer"].count().reset_index()
respondents.rename(columns = {"Answer": "No. of respondents"}, inplace = True)

In [33]:
respondents

        Question  No. of respondents
0      Q10_OTHER                 737
1     Q10_Part_1                9507
2    Q10_Part_10                2051
3    Q10_Part_11                1794
4    Q10_Part_12                 590
..           ...                 ...
357    Q9_Part_5                7468
358    Q9_Part_6                3794
359    Q9_Part_7                3937
360    Q9_Part_8                2839
361    Q9_Part_9                1646

[362 rows x 2 columns]

In [34]:
#Merge respondents to alldata
newdata = pd.merge(alldata,respondents, how = "left", on = "Question")
newdata

,Unique_ID,Q1,Q2,Q3,Q4,Q5,Q6,Question+Subquestion,Answer,Question,No. of respondents
0,1,50-54,Man,India,Bachelorâ€™s degree,Other,5-10 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1,21860
1,2,50-54,Man,Indonesia,Masterâ€™s degree,Program/Project Manager,20+ years,Q7_Part_1-What programming languages do you us...,NaN,Q7_Part_1,21860
2,3,22-24,Man,Pakistan,Masterâ€™s degree,Software Engineer,1-3 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1,21860
3,4,45-49,Man,Mexico,Doctoral degree,Research Scientist,20+ years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1,21860
4,5,45-49,Man,India,Doctoral degree,Other,< 1 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1,21860
...,...,...,...,...,...,...,...,...,...,...,...
9402221,25969,30-34,Man,Egypt,Bachelorâ€™s degree,Data Analyst,1-3 years,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN,Q38_B_OTHER,377
9402222,25970,22-24,Man,China,Masterâ€™s degree,Student,1-3 years,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN,Q38_B_OTHER,377
9402223,25971,50-54,Man,Sweden,Doctoral degree,Research Scientist,I have never written code,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN,Q38_B_OTHER,377
9402224,25972,45-49,Man,United States of America,Masterâ€™s degree,Data Scientist,5-10 years,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN,Q38_B_OTHER,377
9402225,25973,18-21,Man,India,Bachelorâ€™s degree,Business Analyst,I have never written code,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN,Q38_B_OTHER,377

In [35]:
dataC = newdata.copy()
dataC["Q4"] = dataC["Q4"].apply(lambda x: re.sub(r"[^a-zA-Z0-9\s]+", "'", x))

In [36]:
dataC

,Unique_ID,Q1,Q2,Q3,Q4,Q5,Q6,Question+Subquestion,Answer,Question,No. of respondents
0,1,50-54,Man,India,Bachelor's degree,Other,5-10 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1,21860
1,2,50-54,Man,Indonesia,Master's degree,Program/Project Manager,20+ years,Q7_Part_1-What programming languages do you us...,NaN,Q7_Part_1,21860
2,3,22-24,Man,Pakistan,Master's degree,Software Engineer,1-3 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1,21860
3,4,45-49,Man,Mexico,Doctoral degree,Research Scientist,20+ years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1,21860
4,5,45-49,Man,India,Doctoral degree,Other,< 1 years,Q7_Part_1-What programming languages do you us...,Python,Q7_Part_1,21860
...,...,...,...,...,...,...,...,...,...,...,...
9402221,25969,30-34,Man,Egypt,Bachelor's degree,Data Analyst,1-3 years,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN,Q38_B_OTHER,377
9402222,25970,22-24,Man,China,Master's degree,Student,1-3 years,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN,Q38_B_OTHER,377
9402223,25971,50-54,Man,Sweden,Doctoral degree,Research Scientist,I have never written code,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN,Q38_B_OTHER,377
9402224,25972,45-49,Man,United States of America,Master's degree,Data Scientist,5-10 years,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN,Q38_B_OTHER,377
9402225,25973,18-21,Man,India,Bachelor's degree,Business Analyst,I have never written code,"Q38_B_OTHER-In the next 2 years, do you hope t...",NaN,Q38_B_OTHER,377

In [47]:
#df.to_csv("newdata.csv", index = False)

ValueError: This sheet is too large! Your sheet size is: 9402226, 11 Max sheet size is: 1048576, 16384